#!/usr/bin/env bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd $DIR

# Create handout files
ag --tex -l documentclass.beamer | while read filename; do
    echo $filename
    handout="$(echo "$filename" | sed 's/\.tex$//').handout.tex"
    cp "$filename" "$handout"
    sed -i 's/documentclass/documentclass[handout]/' "$handout"
done

# Build all .tex files in their respective folders
find -name '*.tex' | grep -v contributors | xargs latexmk -silent -pdf -cd
find -name '*.tex' | grep -v contributors | xargs latexmk -silent -pdf -cd


function deploy() {
    # Send all PDF files to the website
    find -name '*.pdf' -print0 | rsync -av --files-from=- --from0 ./ khoi@nguyen.me.uk:~/www/files

    # Generate the webpage
    cp web.adoc temp2.adoc
    find -name '*.pdf' | \
        grep -vf blacklist | \
        sed 's/^\.\///;s/\.pdf$//' | sort | \
        xargs -I {} echo -e '| {}\n| link:/files/{}.pdf[icon:file-pdf[]]\n| https://github.com/khoi-nguyen/maths/tree/master/{}.tex[icon:align-justify[]]\n\n' \
        >> temp2.adoc
    echo "|===" >> temp2.adoc

    if ! [ -f temp.adoc ] || ! cmp --silent temp.adoc temp2.adoc; then
        cp temp2.adoc temp.adoc
        scp temp2.adoc khoi@nguyen.me.uk:~/www/teaching.adoc
    fi
    rm temp2.adoc
}

[[ "$USER" == 'khoi' ]] && deploy
